### PR TITLE
📚 DOCS: Adding docs

### PR DESCRIPTION
**Pull request by AakashGfude**
This PR contains the first release of docs.

### CODE REVIEW

**Comment by mmcky** [comment]
hey @AakashGfude we should really be using `jupyterbook` for the docs :-)

**Comment by AakashGfude** [comment]
> hey @AakashGfude we should really be using `jupyterbook` for the docs :-)

hmm. I was using that earlier. But could not get this option https://sphinx-book-theme.readthedocs.io/en/latest/configure.html#use-a-single-page-version-of-this-theme to work in jb config. and since using the same in `sphinx-multitoc-numbering` so did not pay much heed. I will ask in the channel for how to make it work in `jb`

**Comment by AakashGfude** [comment]
@mmcky should I merge this one?

**Comment by mmcky** [comment]
please go ahead 👍

**Pull request merged**
