### PR TITLE
👌 NEW: Initial files, hiddenNode

### PR DESCRIPTION
**Pull request by AakashGfude**
`hide-cell` , `hide-input`, `hide-output`   tags in code-cell are handled to not display them in latex output. 

This is done by replacing the respective node names (CellNode, CellInputNode, CellOutputNode) with hiddenNode (which is just a simple node without any display).

### CODE REVIEW

**Comment by AakashGfude** [comment]
Thanks, @mmcky for your ideas on implementing this. 
@mmcky @choldgraf @chrisjsewell what do you think of this approach to hide output cells. If this looks good I will add similar functionality for `hide-output` and `hide-input` as well.

**Comment by mmcky** [comment]
thanks @AakashGfude -- just to add one thing. By adding these `nodes` to the `sphinx.ast` means we aren't deleting things from the `ast` which is something I think is good as we don't loose information as the `transform` is applied. It also helps with debug and can be updated to support an implementation in `LaTeX` as we find ways to support some of these features in the `static` pdf domain.

**Comment by AakashGfude** [comment]
@mmcky the present push, does replace the `cellNode` with `hiddenNode` 😅  . I think I should wrap the cellNode in `hiddenCellNode` instead of replacing them?

**Comment by mmcky** [comment]
> @mmcky the present push, does replace the `cellNode` with `hiddenNode` 😅 . I think I should wrap the cellNode in `hiddenCellNode` instead of replacing them?

@AakashGfude I guess if we wrap the nodes then we will still need to pair this with the `writer/translator` to `raise nodes.SkipChildren` with a `visit_hiddenNode` method right? I think updating the `node` name is a reasonable thing to do -- the content is still present. I just think deleting things from the AST is the least preferred approach in my view.

**Comment by chrisjsewell** [comment]
cheers @AakashGfude I will try to have a proper look later this week

**Comment by AakashGfude** [comment]
> @AakashGfude I guess if we wrap the nodes then we will still need to pair this with the `writer/translator` to `raise nodes.SkipChildren` with a `visit_hiddenNode` method right? 

I did write a `visie_HiddenCellNode` with `nodes.SkipNode` in it, to be explicit about its intentions.

**Comment by mmcky** [comment]
> > @AakashGfude I guess if we wrap the nodes then we will still need to pair this with the `writer/translator` to `raise nodes.SkipChildren` with a `visit_hiddenNode` method right?
> 
> I did write a `visie_HiddenCellNode` with `nodes.SkipNode` in it, to be explicit about its intentions. Even though name is explicit enough I guess

I think this is the right way to go. Then we don't run the risk of `translators` that have used `visit_unknown` methods causing issues on unknown node types. It is good to be explicit. thanks @AakashGfude

**Comment by mmcky** [comment]
One exception to this might be when we implement `remove-input`, `remove-output`, and `remove-cell` 
https://myst-nb.readthedocs.io/en/latest/use/hiding.html#removing-parts-of-cells

**Comment by AakashGfude** [comment]
I will merge this for now, to setup files in the repo. Please do test the features, and create issues :)

**Pull request merged**
