### PR TITLE
👌 NEW: Improve PDF output for files, part-chapter structure

### PR DESCRIPTION
**Pull request by AakashGfude**
A possible resolution to this issue: https://github.com/executablebooks/jupyter-book/issues/810 .

The primary reason for the issue was two-fold:

-   The subheaders (h2, h3) in master_doc file are all converted to sections in doctree format (and since they are not included **inside the toctree-wrapper node**). So, they show up in the table of contents.

-   the `toctree-wrapper` node was nested inside the last subheader of master_doc, so it was showing up at a lower level than the sections in master_doc in the table of contents.

The implementation I did was:

-  **Remove all the section nodes in master_doc** : for this, I took out all the contents of the section nodes and put it directly inside the master_doc. their titles were changed to bold text.

-  Took out the  `toctree-wrapper` node from the master_doc section node and placed it directly under the document node.

Taking https://github.com/RojerGS/issue810 as the repo to test this,

Before : 
[python.pdf](https://github.com/executablebooks/jupyterbook-latex/files/5557520/python.pdf)

After:
[python.pdf](https://github.com/executablebooks/jupyterbook-latex/files/5557508/python.pdf)

Ofcourse, it needs a bit of formatting and additional work.

What do you think? @mmcky @choldgraf @chrisjsewell 

Also,

 

 https://github.com/executablebooks/jupyter-book/pull/586 functionality is being shifted. to this PR. 

**UPDATE**:

The final list of features in this PR: 

Some LaTex developments in [jupyterbook-latex](https://github.com/executablebooks/jupyterbook-latex) : 

1)  **TOC** : - 

Parts, chapters, sections are being handled in TOC now. With continuous numbering between Parts. Children files (specified with `section` key) in chapters are handled for LaTex by inlining them with the top-level section of the parent file,i.e,  The children file titles are being considered as h2 headers in the parent file. 
`url` key in TOC is ignored in the final PDF output for now, which is what sphinx does as well because of many complications arising from it as outlined in this comment https://github.com/sphinx-doc/sphinx/issues/701#issuecomment-289689442 . 
`tableofContents` node is ignored at the  moment, as it includes the files itself in latex instead of the links (because we are using toctree node). Plan to handle it by converting it to reference nodes for LaTeX.

2) **Master doc**

Master doc page is treated as a front matter page. As an introduction to the book. It does not appear in the TOC. All the pages section and subsections are converted to bolded text of varying sizes, based on the level of the section.

4)  **Others**

Changing table of contents title to `Contents` . Using `myst_amsmath_enable` flag to render math.  Using a theme file called `jupyterBook.cls` to load packages and writing latex commands. Handling `gif` and `png` image formats.

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @AakashGfude -- this is looking promising as a way to adjust the `frontmatter` headers. 

- [ ] I think the text should preserve new paragraphs so that the headers are bold and the text is not bold. 
- [ ] the PR includes `docs` for `sphinx-multitoc-numbering` (which must be an error)?

**Comment by AakashGfude** [comment]
@mmcky what do you think of the new formatting. 

[python.pdf](https://github.com/executablebooks/jupyterbook-latex/files/5570091/python.pdf)

I am also trying out some ideas to vary font sizes for H3, H2 headers, etc. At present identifying the levels of the header is a bit tricky. But, will be completed soon.

**Comment by mmcky** [comment]
thanks @AakashGfude that looks nice. It is a huge improvement.

**Comment by mmcky** [comment]
> At present identifying the levels of the header is a bit tricky.

@AakashGfude usually `depth` is in the `node.attributes` of a section.

**Comment by choldgraf** [comment]
Just to make sure I get this.

Say you have `index.md` like this:

````md
# My title

## H2 1

```{toctree}
page1
page2
```
````

then the *old* way the book would be structured is:

```
- My title
 - H2 1
   - page1 title
   - page2 title
```

and the new way the book would be structured is

```
- My title (H2 1 is now just bolded text)
  - page1 title
  - page2 title
```
  
Is that correct? If so, a couple questions:

1. I assume this behavior is the same for H3/4/5/etc headers right?
2. And this behavior *only* applies to the `masterdoc` file right?
3. How does (or how should) this apply to *section* headers? E.g. if you had a structure like:

   ```
   chapter: myfile
   - sections:
     - file: mysectionintro
       sections:
         - file: mysection
   ```
   Many folks would use `mysectionintro` as a similar "introductory" section, and they'd similarly want the H2/H3 headers of `mysectionintro` to not be the parents of the headers in `mysection`.

**Comment by choldgraf** [comment]
Note that this also seems like it could be relevant to https://github.com/executablebooks/jupyter-book/issues/1017 as well, right @AakashGfude ?

**Comment by AakashGfude** [comment]
Thanks, @choldgraf  for reviewing this.

> - My title (H2 1 is now just bolded text)
>   - page1 title
>   - page2 title
> ```

Correct. H2 will be a bolded text with a bigger font, then surrounding texts, and h3, h4 headers.

> 1. I assume this behavior is the same for H3/4/5/etc headers right?

Right. With the font size decreasing as we go down.

> 2. And this behavior _only_ applies to the `masterdoc` file right?

Yes, at present.

> 3. How does (or how should) this apply to _section_ headers? E.g. if you had a structure like:
>    ```
>    chapter: myfile
>    - sections:
>      - file: mysectionintro
>        sections:
>          - file: mysection
>    ```

I guess we will have to implement a similar approach to this. `jb` docs is a nice test case.

**Comment by AakashGfude** [comment]
> Note that this also seems like it could be relevant to [executablebooks/jupyter-book#1017](https://github.com/executablebooks/jupyter-book/issues/1017) as well, right @AakashGfude ?

Yes, it looks very relevant to that. But I guess, with the current implementation, after bolding the headers, we will lose its ability to get numbered?

That example would then become?

```
1. My title
   My header (a header inside My title but not in table of contents)
1.1 Page 1 title
```

**Comment by AakashGfude** [comment]
Merging this one. Will add docs, tests, and other features/fixes in subsequent PRs.

**Pull request merged**
