### PR TITLE
🔧 MAINTAIN: Update package name to sphinx-jupyterbook-latex

### LINKED ISSUE #61: Rename extension sphinx-jupyterbook-latex
**Is your feature request related to a problem? Please describe.**

This is now a `sphinx` extension based on #55 so we should rename this to be `sphinx-`

Candidates include:

1. `sphinx-jupyterbook-latex`
2. `sphinx-jb-latex`

I think the first option is pretty good. 
While it links this extension to `jupyterbook` (which is essentially not needed) but I think `sphinx-latex` is too generic.

Opening this issue for discussion before making the change

cc: @chrisjsewell @choldgraf @AakashGfude

### PR DESCRIPTION
**Pull request by mmcky**
This PR updates this package name to be `sphinx-jupyterbook-latex` and fixes #61 

PR #55 updated the package to be dependant on `sphinx` rather than `jupyterbook` so this rename more closely aligns with the package and how it is implemented as a `sphinx extension`. 

This package still contains the `latex` infrastructure for `jupyter-book`

### CODE REVIEW

**Comment by mmcky** [comment]
- [ ] rename actual `github repo`
- [ ] Setup via PyPI
- [ ] Setup via Conda Forge

**Comment by mmcky** [comment]
@chrisjsewell @AakashGfude there is one failing test but that is expected as it is trying to run `jb build` and that upstream tool hasn't been updated yet.

**Comment by mmcky** [comment]
- [ ] what should be done around `jupyterbook-latex` links in the CHANGELOG.md. I guess they should be updated to `sphinx-jupyterbook-latex` given the name change and so they continue to resolve. @chrisjsewell do you agree?

Alternatively we could start a fresh repo but I don't think that makes sense.

**Comment by mmcky** [comment]
I think just renaming this repo is OK so I have update links in `CHANGELOG` to `sphinx-jupyterbook-latex` so they continue to link.

**Comment by mmcky** [comment]
This PR https://github.com/executablebooks/jupyter-book/pull/1340 needs to be tested once this is released

**Comment by mmcky** [comment]
@chrisjsewell will I need to register this new package name with `PyPI` or will the `publish` workflow register it when it `publishes` via the `v*` tag rule?

**Comment by mmcky** [comment]
- [x] this has been tested against git+https://github.com/executablebooks/jupyter-book@sphinx-jupyterbook-latex in a local environment. @chrisjsewell I couldn't figure out how to specify a `git+https` install in `setup.cfg` to test via GitHub Actions.

**Comment by mmcky** [comment]
@AakashGfude would you have time to review this PR?

**Comment by mmcky** [comment]
The only failing test is the `jupyter-book` test that requires https://github.com/executablebooks/jupyter-book/pull/1340

**Comment by mmcky** [comment]
@AakashGfude once you have had a chance to review and/or approve -- I will merge this and issue a new release.

**Review by AakashGfude — APPROVED** [review]
Have tested after making necessary changes to `jupyter-book`. The failing test in this one is passing. So, this is good to go from my end 🎉

**Comment by mmcky** [comment]
thanks @AakashGfude I will change the name once `jupyter-book=0.11` is released so it will be included in the next minor release `jupyter-book=0.11.1`

**Comment by mmcky** [comment]
@choldgraf @chrisjsewell what is best practice re: name change `release`. Should we:

1. **rename this repository** and start issuing `sphinx-jupyterbook-latex`
2. **archive this repository** and setup a new repo named `sphinx-jupyterbook-latex` then deploy to `pypi`

Just thinking through `pypi` and starting to think Option 2 is the best route but thought I would see what you think.

**Comment by chrisjsewell** [comment]
Oh no definitely just rename the repo.

**Comment by mmcky** [comment]
OK cool -- thanks @chrisjsewell wasn't sure if a rename would mess up `pypi` history. But looks like `pypi` tar files are hosted by pypi (rather than fetching from github)

**Comment by chrisjsewell** [comment]
Well pypi doesn't even care what the repo name is (of course packages can come from anywhere not just GitHub), it cares what the package name is, which are two distinct things

**Comment by chrisjsewell** [comment]
Yeh and pypi doesn't fetch from GitHub in anyway, you push to pypi

**Pull request merged**
